name: supreme
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http_proxy: 1.1.0
  flutter_inappwebview: 5.1.0+4
  provider_for_redux: 2.0.0
  async_redux: 9.0.0
  awesome_dialog: 1.3.2
  flutter_proxy: ^0.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
